using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Runtime.CompilerServices;
using MSBuildGuard.Core.Baseline;

namespace MSBuildGuard.VisualStudio.ToolWindows
{
	/// <summary>
	/// Represents an individual trust suggestion item in the UI.
	/// </summary>
	public sealed class TrustSuggestionItemViewModel : INotifyPropertyChanged
	{
		private bool isSelected;

		/// <summary>
		/// Initializes a new instance of the <see cref="TrustSuggestionItemViewModel"/> class.
		/// </summary>
		/// <param name="suggestion">The underlying core suggestion.</param>
		public TrustSuggestionItemViewModel(TrustSuggestion suggestion)
		{
			this.Suggestion = suggestion ?? throw new ArgumentNullException(nameof(suggestion));
			this.isSelected = suggestion.IsSelected;
		}

		/// <summary>
		/// Occurs when a property value changes.
		/// </summary>
		public event PropertyChangedEventHandler? PropertyChanged;

		/// <summary>
		/// Gets the underlying trust suggestion.
		/// </summary>
		public TrustSuggestion Suggestion { get; }

		/// <summary>
		/// Gets or sets a value indicating whether this suggestion is selected for trust.
		/// </summary>
		public bool IsSelected
		{
			get => this.isSelected;
			set
			{
				if (this.isSelected == value)
				{
					return;
				}

				this.isSelected = value;
				this.Suggestion.IsSelected = value;
				this.OnPropertyChanged();
			}
		}

		/// <summary>
		/// Gets the display name of the suggestion.
		/// </summary>
		public string DisplayName => this.Suggestion.DisplayName;

		/// <summary>
		/// Gets the trust scope category name.
		/// </summary>
		public string ScopeName => this.Suggestion.Scope.ToString();

		/// <summary>
		/// Gets the recommendation reasoning.
		/// </summary>
		public string RecommendationReason => this.Suggestion.RecommendationReason;

		/// <summary>
		/// Gets the source of reputation rating.
		/// </summary>
		public string ReputationSourceDescription => this.Suggestion.ReputationSourceDescription;

		private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
		{
			this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}

	/// <summary>
	/// View model managing onboarding trust suggestions.
	/// </summary>
	public sealed class BaselineOnboardingViewModel : INotifyPropertyChanged
	{
		private bool createBaselineForRemaining = true;
		private bool doNotScanAgain;
		private bool dontShowAgain;
		private string selectedTrustScope = "Solution";

		/// <summary>
		/// Initializes a new instance of the <see cref="BaselineOnboardingViewModel"/> class.
		/// </summary>
		/// <param name="suggestions">Core suggestions generated by analysis.</param>
		public BaselineOnboardingViewModel(IEnumerable<TrustSuggestion> suggestions)
		{
			if (suggestions == null)
			{
				throw new ArgumentNullException(nameof(suggestions));
			}

			this.Suggestions = new ObservableCollection<TrustSuggestionItemViewModel>();

			foreach (var suggestion in suggestions)
			{
				this.Suggestions.Add(new TrustSuggestionItemViewModel(suggestion));
			}
		}

		/// <summary>
		/// Occurs when a property value changes.
		/// </summary>
		public event PropertyChangedEventHandler? PropertyChanged;

		/// <summary>
		/// Gets the available trust scope options.
		/// </summary>
		public List<string> AvailableTrustScopes { get; } = new List<string> { "User", "Solution", "Project" };

		/// <summary>
		/// Gets or sets the chosen trust scope level.
		/// </summary>
		public string SelectedTrustScope
		{
			get => this.selectedTrustScope;
			set
			{
				if (this.selectedTrustScope == value)
				{
					return;
				}

				this.selectedTrustScope = value;
				this.OnPropertyChanged();
			}
		}

		/// <summary>
		/// Gets the observable collection of suggestions.
		/// </summary>
		public ObservableCollection<TrustSuggestionItemViewModel> Suggestions { get; }

		/// <summary>
		/// Gets or sets a value indicating whether to create a baseline for remaining findings.
		/// </summary>
		public bool CreateBaselineForRemaining
		{
			get => this.createBaselineForRemaining;
			set
			{
				if (this.createBaselineForRemaining == value)
				{
					return;
				}

				this.createBaselineForRemaining = value;
				this.OnPropertyChanged();
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether to disable scanning for this solution completely.
		/// </summary>
		public bool DoNotScanAgain
		{
			get => this.doNotScanAgain;
			set
			{
				if (this.doNotScanAgain == value)
				{
					return;
				}

				this.doNotScanAgain = value;
				this.OnPropertyChanged();
			}
		}

		/// <summary>
		/// Gets or sets a value indicating whether to suppress future onboarding prompts for this solution.
		/// </summary>
		public bool DontShowAgain
		{
			get => this.dontShowAgain;
			set
			{
				if (this.dontShowAgain == value)
				{
					return;
				}

				this.dontShowAgain = value;
				this.OnPropertyChanged();
			}
		}

		private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
		{
			this.PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
