//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace MSBuildGuard.VisualStudio.Resources
{
	using System;

	/// <summary>
	///   A strongly-typed resource class.
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class VSPackage
	{
		private static global::System.Resources.ResourceManager? resourceMan;

		private static global::System.Globalization.CultureInfo? resourceCulture;

		internal VSPackage()
		{
		}

		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (object.ReferenceEquals(resourceMan, null))
				{
					var temp = new global::System.Resources.ResourceManager("MSBuildGuard.VisualStudio.Resources.VSPackage", typeof(VSPackage).Assembly);

					resourceMan = temp;
				}

				return resourceMan;
			}
		}

		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo? Culture
		{
			get
			{
				return resourceCulture;
			}

			set
			{
				resourceCulture = value;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to Project Security Review integration for Visual Studio.
		/// </summary>
		internal static string PackageDescription
		{
			get
			{
				return ResourceManager.GetString("PackageDescription", resourceCulture) ?? string.Empty;
			}
		}

		/// <summary>
		///   Looks up a localized string similar to MSBuild Guard for Visual Studio.
		/// </summary>
		internal static string PackageTitle
		{
			get
			{
				return ResourceManager.GetString("PackageTitle", resourceCulture) ?? string.Empty;
			}
		}
	}
}
